version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    command:
      - postgres
      - -c
      - wal_level=logical #required for MaterializedPostgreSQL
    # Uncomment to make changes in DB persistent
    #volumes:
    #  - ./volumes/postgres:/var/lib/postgresql/data
    env_file:
      - .env
  migrations:
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    env_file:
      - .env
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - FLYWAY_SCHEMAS=flyway,${POSTGRES_SCHEMA}
    depends_on:
      - postgres
  # reference: https://github.com/ClickHouse/examples/blob/main/docker-compose-recipes/recipes/ch-and-postgres/docker-compose.yaml
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - postgres
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./configs/data-sources.yml:/etc/grafana/provisioning/datasources/config.yml
    env_file:
      - .env